---
title: "Using Meaning Extraction Method (MEM) to Find the Themes in Justified vs. Unjustified Anger Narratives"
author: "Pooya Razavi"
date: "2022-12-27"
output: 
  html_document:
    toc: true
    theme: united
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, warning=FALSE}
#load libraries
package_list <- c("dplyr", "tidyr", "ggplot2", "tidytext", "topicmodels", "rlang")
lapply(package_list, require, character.only = TRUE)

#####Load the datasets

#Justified Anger

justified_df_binary <- read.csv("C:/Users/Pooya/Dropbox (University of Oregon)/Anger Dissertation/LIWC/MEM/justified_ngram1 threshold2_5percent/LIWC-22 Results - justified_df_for_MEM - MEM Binary.csv")

justified_word_frequency <- read.csv("C:/Users/Pooya/Dropbox (University of Oregon)/Anger Dissertation/LIWC/MEM/justified_ngram1 threshold2_5percent/LIWC-22 Results - justified_df_for_MEM - MEM Frequencies.csv")

#find and remove words with >= 30% frequency
justified_word_list <- justified_word_frequency %>% 
              filter(Percentage.of.Rows.with.Word >= 30 | Percentage.of.Rows.with.Word < 5) %>% 
              select(Word, Percentage.of.Rows.with.Word)

justified_df_binary1 <- justified_df_binary %>% 
                select(-justified_word_list$Word)


#Unjustified Anger

unjustified_df_binary <- read.csv("C:/Users/Pooya/Dropbox (University of Oregon)/Anger Dissertation/LIWC/MEM/unjustified_ngram1 threshold2_5percent/LIWC-22 Results - unjustified_df_for_MEM - MEM Binary.csv")

unjustified_word_frequency <- read.csv("C:/Users/Pooya/Dropbox (University of Oregon)/Anger Dissertation/LIWC/MEM/unjustified_ngram1 threshold2_5percent/LIWC-22 Results - unjustified_df_for_MEM - MEM Frequencies.csv")

#find and remove words with >= 30% frequency
unjustified_word_list <- unjustified_word_frequency %>% 
              filter(Percentage.of.Rows.with.Word >= 30 | Percentage.of.Rows.with.Word < 5) %>% 
              select(Word)

unjustified_df_binary1 <- unjustified_df_binary %>% 
                select(-unjustified_word_list$Word)

knitr::opts_chunk$set(echo = TRUE)
```

# Functions

```{r pca_table_function}
#Function to create a table from the pattern matrix
#x is the correlation matrix
#nfac is the number of components/factors

pca_pattern_table <- function(x, nfac){
  pca_nf_comp <- x %>%  
                psych::principal(nfactors = nfac)
  
  nf_comp_outcome <- psych::kaiser(pca_nf_comp, rotate = "Varimax") %>% psych::fa.sort()
  
  nf_comp_outcome[["loadings"]] %>% 
                    knitr::kable(digits = 2) %>%
                    kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>% 
                    kableExtra::kable_paper(full_width = F)
}

##for example, with the below tetrachoric correlation matrix
#tetra_matrix <- df_binary1 %>% 
#                  select(justify:pretty) %>% 
#                    psych::tetrachoric()
##the function works like this
#pca_pattern_table(x = tetra_matrix[["rho"]], nfac = 5)
```


```{r pca_wordcloud_function}
#Function to create a wordcloud of the top words with loadings >= threshold
  #x is the correlation matrix
  #nfac is the number of components/factors
  #nword is the number of words included in the word cloud (default = 15)
  #thresh determines which words (based on their component loading) should be filtered out. Default is to include the words with loadings greater than or equal 0.30

top_words_cloud <- function(x, nfac, nword = 15, thresh = 0.30){
    
  pca_nf_comp <- x %>%  
                psych::principal(nfactors = nfac)
  
  nf_comp_outcome <- psych::kaiser(pca_nf_comp, rotate = "Varimax") %>% psych::fa.sort()
  
  top_words_filtered <- nf_comp_outcome[["loadings"]] %>% 
                        as.data.frame() %>% 
                        tibble::rownames_to_column("Word") %>% 
                        pivot_longer(cols = contains("RC"),
                                     names_to = "Component",
                                     values_to = "Loading") %>% 
                        group_by(Component) %>% 
                                      slice_max(Loading, n = nword) %>% 
                                      ungroup() %>% 
                                      arrange(Component, -Loading) %>% 
                        mutate(Word = forcats::fct_reorder(Word, Loading)) %>% 
                        filter(Loading >= thresh) %>% 
                        mutate(Component = stringr::str_replace(Component, "RC", "Theme "))

top_words_filtered %>% 
    ggplot(aes(label = Word, size = Loading, color = factor(sample.int(10, nrow(top_words_filtered), replace = TRUE)))) +
    ggwordcloud::geom_text_wordcloud(rm_outside = TRUE, family = "serif") +
    scale_size_area(max_size = 9) +
    facet_wrap(~ Component) +
    theme_minimal(base_family = "serif", base_size = 14)
}

##for example, with the below tetrachoric correlation matrix
#tetra_matrix <- df_binary1 %>% 
#                  select(justify:pretty) %>% 
#                    psych::tetrachoric()
##the function works like this
#top_words_cloud(x = tetra_matrix[["rho"]], nfac = 4)
```


```{r pca_barchart_function}
#Function to create a barchart of the top words with loadings >= threshold

top_words_barchart <- function(x, nfac, nword = 15, thresh = 0.30){
    
  pca_nf_comp <- x %>%  
                psych::principal(nfactors = nfac)
  
  nf_comp_outcome <- psych::kaiser(pca_nf_comp, rotate = "Varimax") %>% psych::fa.sort()
  
  top_loading_words <- nf_comp_outcome[["loadings"]] %>% 
                          as.data.frame() %>% 
                          tibble::rownames_to_column("Word") %>% 
                          pivot_longer(cols = contains("RC"),
                                       names_to = "Component",
                                       values_to = "Loading") %>% 
                          group_by(Component) %>% 
                                        slice_max(Loading, n = nword) %>% 
                                        ungroup() %>% 
                                        arrange(Component, -Loading)
  
  
  top_loading_words %>% 
    group_by(Component) %>% 
    mutate(Word = forcats::fct_reorder(Word, Loading)) %>% 
    #ungroup() %>% 
    filter(Loading >= thresh) %>% 
        ggplot(aes(Loading, Word, fill = factor(Component))) + 
        geom_col(show.legend = FALSE) + 
        facet_wrap(~ Component, scales = "free")

}

#example
#top_words_barchart(x = tetra_matrix[["rho"]], nfac = 4)
```

# Simple Wordclouds for Each Anger Type

```{r}

rbind(justified_word_frequency, unjustified_word_frequency) %>% 
  filter(Percentage.of.Rows.with.Word <= 30 & Percentage.of.Rows.with.Word > 5) %>% 
  psych::describe() %>% 
  as.data.frame() %>% 
  filter(vars == 4)

# high frequency words

## Justified Anger

justified_word_frequency %>% 
  filter(Percentage.of.Rows.with.Word <= 30 & Percentage.of.Rows.with.Word >= 8.0821) %>% 
  ggplot(data = ., aes(label = Word, size = Percentage.of.Rows.with.Word, color = factor(sample.int(10, nrow(.), replace = TRUE)))) +
    ggwordcloud::geom_text_wordcloud(rm_outside = TRUE, family = "serif") +
    scale_size_area(max_size = 11) +
    labs(title = "Justified Anger",
         subtitle = "Above Median Frequency Words") +
    theme_minimal(base_family = "serif")

## Unjustified Anger

unjustified_word_frequency %>% 
  filter(Percentage.of.Rows.with.Word <= 30 & Percentage.of.Rows.with.Word >= 8.0821) %>% 
  ggplot(data = ., aes(label = Word, size = Percentage.of.Rows.with.Word, color = factor(sample.int(10, nrow(.), replace = TRUE)))) +
    ggwordcloud::geom_text_wordcloud(rm_outside = TRUE, family = "serif") +
    scale_size_area(max_size = 11) +
    labs(title = "Unjustified Anger",
         subtitle = "Above Median Frequency Words") +
    theme_minimal(base_family = "serif")


# low frequency words

## Justified Anger

justified_word_frequency %>% 
  filter(Percentage.of.Rows.with.Word < 8.0821 & Percentage.of.Rows.with.Word >= 5) %>% 
  ggplot(data = ., aes(label = Word, size = Percentage.of.Rows.with.Word^2, color = factor(sample.int(10, nrow(.), replace = TRUE)))) +
    ggwordcloud::geom_text_wordcloud(rm_outside = TRUE, family = "serif") +
    scale_size_area(max_size = 9) +
    labs(title = "Justified Anger",
         subtitle = "Below Median Frequency Words") +
    theme_minimal(base_family = "serif")

## Unjustified Anger

unjustified_word_frequency %>% 
  filter(Percentage.of.Rows.with.Word < 8.0821 & Percentage.of.Rows.with.Word >= 5) %>% 
  ggplot(data = ., aes(label = Word, size = Percentage.of.Rows.with.Word^2, color = factor(sample.int(10, nrow(.), replace = TRUE)))) +
    ggwordcloud::geom_text_wordcloud(rm_outside = TRUE, family = "serif") +
    scale_size_area(max_size = 9) +
    labs(title = "Unjustified Anger",
         subtitle = "Below Median Frequency Words") +
    theme_minimal(base_family = "serif")

```

# Justified Anger MEM

## Tetrachoric - PCA

```{r}
#create a tetrachoric correlation matrix
tetra_matrix_just <- justified_df_binary1 %>% 
                  select(justify:deal) %>% 
                    psych::tetrachoric()
#scree plot
tetra_matrix_just[["rho"]] %>% 
  psych::scree(hline = -1, factors = FALSE)


#5c
pca_pattern_table(x = tetra_matrix_just[["rho"]], nfac = 5)
top_words_cloud(x = tetra_matrix_just[["rho"]], nfac = 5, thresh = 0.2)
top_words_barchart(x = tetra_matrix_just[["rho"]], nfac = 5)

#6c
pca_pattern_table(x = tetra_matrix_just[["rho"]], nfac = 6)
top_words_cloud(x = tetra_matrix_just[["rho"]], nfac = 6, thresh = 0.2)
top_words_barchart(x = tetra_matrix_just[["rho"]], nfac = 6)

```

## Pearson - PCA

```{r}
#create a pearson correlation matrix
pearson_matrix_just <- justified_df_binary1 %>% 
                  select(justify:deal) %>% 
                    cor()
#scree plot
just_scree <- pearson_matrix_just %>% 
  psych::scree(hline = -1, factors = FALSE)

data.frame(Component = c(1:length(just_scree$pcv)),
           EigenValues = just_scree$pcv
                         ) %>% 
  ggplot(aes(x = Component, y = EigenValues)) +
  geom_line() +
  geom_point(color = "darkblue") +
  labs(title = "Justified Anger",
       y = "Eigen Values") +
  lims(x = c(1, 80)) +
  theme_bw(base_family = "serif")

#5c (*)
pca_pattern_table(x = pearson_matrix_just, nfac = 5)
top_words_cloud(x = pearson_matrix_just, nfac = 5, thresh = 0.25)
top_words_barchart(x = pearson_matrix_just, nfac = 5)

#6c
pca_pattern_table(x = pearson_matrix_just, nfac = 6)
top_words_cloud(x = pearson_matrix_just, nfac = 6, thresh = 0.25)
top_words_barchart(x = pearson_matrix_just, nfac = 6)

#7c
pca_pattern_table(x = pearson_matrix_just, nfac = 7)
top_words_cloud(x = pearson_matrix_just, nfac = 7, thresh = 0.25)
top_words_barchart(x = pearson_matrix_just, nfac = 7)

#9c
pca_pattern_table(x = pearson_matrix_just, nfac = 9)
top_words_cloud(x = pearson_matrix_just, nfac = 9, thresh = 0.25)
top_words_barchart(x = pearson_matrix_just, nfac = 9)


```

# Unjustified Anger MEM

## tetrachoric - PCA

```{r}
#create a tetrachoric correlation matrix
tetra_matrix_unjust <- unjustified_df_binary1 %>% 
                  select(justify:car) %>% 
                    psych::tetrachoric()
#scree plot
tetra_matrix_unjust[["rho"]] %>% 
  psych::scree(hline = -1, factors = FALSE)


#4c
pca_pattern_table(x = tetra_matrix_unjust[["rho"]], nfac = 4)
top_words_cloud(x = tetra_matrix_unjust[["rho"]], nfac = 4, thresh = 0.2)
top_words_barchart(x = tetra_matrix_unjust[["rho"]], nfac = 4)

#7c
pca_pattern_table(x = tetra_matrix_unjust[["rho"]], nfac = 7)
top_words_cloud(x = tetra_matrix_unjust[["rho"]], nfac = 7, thresh = 0.2)
top_words_barchart(x = tetra_matrix_unjust[["rho"]], nfac = 7)

```

## Pearson - PCA

```{r}
#create a pearson correlation matrix
pearson_matrix_unjust <- unjustified_df_binary1 %>% 
                  select(justify:car) %>% 
                    cor()
#scree plot
unjust_scree <- pearson_matrix_unjust %>% 
  psych::scree(hline = -1, factors = FALSE)

data.frame(Component = c(1:length(unjust_scree$pcv)),
           EigenValues = unjust_scree$pcv
                         ) %>% 
  ggplot(aes(x = Component, y = EigenValues)) +
  geom_line() +
  geom_point(color = "darkgreen") +
  labs(title = "Unjustified Anger",
       y = "Eigen Values") +
  lims(x = c(1, 80)) +
  theme_bw(base_family = "serif")

#4c
pca_pattern_table(x = pearson_matrix_unjust, nfac = 4)
top_words_cloud(x = pearson_matrix_unjust, nfac = 4, thresh = 0.2)
top_words_barchart(x = pearson_matrix_unjust, nfac = 4)

#6c
pca_pattern_table(x = pearson_matrix_unjust, nfac = 6)
top_words_cloud(x = pearson_matrix_unjust, nfac = 6, thresh = 0.25)
top_words_barchart(x = pearson_matrix_unjust, nfac = 6)

#7c 
pca_pattern_table(x = pearson_matrix_unjust, nfac = 7)
top_words_cloud(x = pearson_matrix_unjust, nfac = 7, thresh = 0.25)
top_words_barchart(x = pearson_matrix_unjust, nfac = 7)

#9c (*)
pca_pattern_table(x = pearson_matrix_unjust, nfac = 9)
top_words_cloud(x = pearson_matrix_unjust, nfac = 9, thresh = 0.25)
top_words_barchart(x = pearson_matrix_unjust, nfac = 9)

#11c
pca_pattern_table(x = pearson_matrix_unjust, nfac = 11)
top_words_cloud(x = pearson_matrix_unjust, nfac = 11, thresh = 0.25)
top_words_barchart(x = pearson_matrix_unjust, nfac = 11)

```

