---
title: "MEM-based Dictionaries"
author: "Pooya Razavi"
date: "2022-12-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#load libraries
package_list <- c("dplyr", "tidyr", "ggplot2", "tidytext", "topicmodels", "rlang")
lapply(package_list, require, character.only = TRUE)

#read in the cleaned-up df (used in LIWC for MEM)
df <- read.csv("C:/Users/pooya/Dropbox (University of Oregon)/Anger Dissertation/LIWC/MEM/df_for_MEM.csv") %>% 
                      select(-X)

#read in the pattern matrix (produced in the MEM_narratives.RMD)
pattern_matrix <- read.csv("mem_pca_8c_pattern_matrix.csv") %>% 
                      select(-X)

knitr::opts_chunk$set(echo = TRUE)
```

# Functions

```{r}
#Function to report independent-samples t-test
  ind_ttest_report <- function(iv, dv) {
      ttest <- t.test(dv ~ iv)
      effect_size <- effectsize::cohens_d(dv ~ iv, pooled_sd = FALSE)
      t <- ttest[["statistic"]] %>% round(2)
      df <- ttest[["parameter"]] %>% round(1)
      original_p <- ttest[["p.value"]] %>% round(3)
      p <- if_else(original_p >= .001, paste0("= ", as.character(original_p)), "< .001")
      d <- effect_size[1,1] %>% round(2)    
      
      print(paste0("t(", df, ") = ", t, ", p ", p, ", d = ", d))
      
  }
```



# Create Dictionaries

```{r}
extract_top_words_weights <- function(pattern_matrix, component, thresh = 0.3){

  pattern_matrix %>% 
    select(word, {{component}}) %>% 
    filter({{component}} >= thresh)
  
}    
  
theme_1 <- extract_top_words_weights(pattern_matrix, component = RC1, thresh = .30)
theme_2 <- extract_top_words_weights(pattern_matrix, component = RC2, thresh = .30)
theme_3 <- extract_top_words_weights(pattern_matrix, component = RC3, thresh = .30)
theme_4 <- extract_top_words_weights(pattern_matrix, component = RC4, thresh = .30)
theme_5 <- extract_top_words_weights(pattern_matrix, component = RC5, thresh = .30)
theme_6 <- extract_top_words_weights(pattern_matrix, component = RC6, thresh = .30)
theme_7 <- extract_top_words_weights(pattern_matrix, component = RC7, thresh = .30)
theme_8 <- extract_top_words_weights(pattern_matrix, component = RC8, thresh = .30)


```

# Preprocessing

```{r}
tokenized_narratives <- df %>% 
                            tidytext::unnest_tokens(input = all_narratives,
                                                    output = word,
                                                    format = "text",
                                                    token = "words",
                                                    drop = TRUE,
                                                    to_lower = TRUE) %>% 
                            anti_join(stop_words)

```

# Apply the dictionary

This is by weighting the words based on the component loadings. Not very robust...

```{r}
theme_1$word[3] <- "break"


tokens_w_theme_1 <- tokenized_narratives %>% 
                          inner_join(theme_1)

#tokens_w_theme_1 %>% 
#  group_by(ResponseId) %>% 
#  mutate(theme_1 = mean(RC1)) 

narratives_w_theme1 <- tokens_w_theme_1 %>% 
                          group_by(ResponseId) %>% 
                          summarise(aggregate_value = sum(RC1)) %>% 
                          ungroup() %>% 
                          inner_join(df) %>% 
                          select(ResponseId, Condition, all_narratives, aggregate_value)

psych::describeBy(narratives_w_theme1$aggregate_value, group = narratives_w_theme1$Condition)  
ind_ttest_report(narratives_w_theme1$Condition, narratives_w_theme1$aggregate_value)

```


```{r}
tokens_w_theme_1_dich <- df %>% 
                            tidytext::unnest_tokens(input = all_narratives,
                                                    output = word,
                                                    format = "text",
                                                    token = "words",
                                                    drop = TRUE,
                                                    to_lower = TRUE) %>% 
                            anti_join(stop_words) %>% 
                            mutate(theme_1 = if_else(word %in% theme_1$word, 1, 0))

narratives_w_theme1_dich <- tokens_w_theme_1_dich %>% 
                                group_by(ResponseId) %>% 
                                summarise(freq = sum(theme_1)) %>% 
                                filter(freq != 0) %>% 
                                ungroup() %>% 
                                inner_join(df) %>% 
                                mutate(word_count = stringr::str_count(all_narratives ,"\\W+")) %>% 
                                mutate(rel_freq = freq*100/word_count,
                                       theme_presence = if_else(freq > 2, "Y", "N")) %>% 
                                select(ResponseId, Condition, all_narratives, word_count, freq, rel_freq)

#frequency
psych::describeBy(narratives_w_theme1_dich$freq, group = narratives_w_theme1_dich$Condition)
ind_ttest_report(narratives_w_theme1_dich$Condition, narratives_w_theme1_dich$freq)

#relative frequency
psych::describeBy(narratives_w_theme1_dich$rel_freq, group = narratives_w_theme1_dich$Condition)
ind_ttest_report(narratives_w_theme1_dich$Condition, narratives_w_theme1_dich$rel_freq)

cor.test(narratives_w_theme1_dich$freq, narratives_w_theme1_dich$rel_freq, method = c("pearson"))[["estimate"]]
cor.test(narratives_w_theme1_dich$freq, narratives_w_theme1_dich$rel_freq, method = c("spearman"))[["estimate"]]

```

```{r}
calc_mem_diff <- function(theme_words) {
  tokens_w_theme_dich <- df %>% 
                            tidytext::unnest_tokens(input = all_narratives,
                                                    output = word,
                                                    format = "text",
                                                    token = "words",
                                                    drop = TRUE,
                                                    to_lower = TRUE) %>% 
                            anti_join(stop_words) %>% 
                            mutate(theme = if_else(word %in% theme_words, 1, 0))
  
  narratives_w_theme_dich <- tokens_w_theme_dich %>% 
                                group_by(ResponseId) %>% 
                                summarise(freq = sum(theme)) %>% 
                                filter(freq != 0) %>% 
                                ungroup() %>% 
                                inner_join(df) %>% 
                                mutate(word_count = stringr::str_count(all_narratives ,"\\W+")) %>% 
                                mutate(rel_freq = freq*100/word_count,
                                       theme_presence = if_else(freq > 2, "Y", "N")) %>% 
                                select(ResponseId, Condition, all_narratives, word_count, freq, rel_freq, theme_presence)
  print(">>>FREQUENCY")
  psych::describeBy(narratives_w_theme_dich$freq, group = narratives_w_theme_dich$Condition, mat = TRUE) %>% print()
  ind_ttest_report(narratives_w_theme_dich$Condition, narratives_w_theme_dich$freq)
  print(">>>RELATIVE FREQUENCY")
  psych::describeBy(narratives_w_theme_dich$rel_freq, group = narratives_w_theme_dich$Condition, mat = TRUE) %>% print()
  ind_ttest_report(narratives_w_theme_dich$Condition, narratives_w_theme_dich$rel_freq)
  print(">>>PRESENCE/ABSENCE OF THEME")
  table(narratives_w_theme_dich$Condition, narratives_w_theme_dich$theme_presence) %>% print()
  chisq.test(narratives_w_theme_dich$Condition, narratives_w_theme_dich$theme_presence, correct=FALSE) %>% print()
  print(">>> RELATION BETWEEN THE TWO")
  cor.test(narratives_w_theme_dich$freq, narratives_w_theme_dich$rel_freq, method = c("pearson"))[["estimate"]] %>% print()
  #cor.test(narratives_w_theme_dich$freq, narratives_w_theme_dich$rel_freq, method = c("spearman"))[["estimate"]] %>% print()
}

calc_mem_diff(theme_1$word)

calc_mem_diff(theme_2$word)

calc_mem_diff(theme_3$word)

calc_mem_diff(theme_4$word)

calc_mem_diff(theme_5$word)

calc_mem_diff(theme_6$word)

calc_mem_diff(theme_7$word)

calc_mem_diff(theme_8$word)



```




What if we create a theme 1 that is inclusive of all the 92 terms?
Doesn't solve anything!
```{r}
theme_1_inclusive <- pattern_matrix %>% 
                        select(word, RC1)

tokens_w_theme_1_inclusive <- tokenized_narratives %>% 
                                  inner_join(theme_1_inclusive)

narratives_w_theme1_inclusive <- tokens_w_theme_1_inclusive %>% 
                                    group_by(ResponseId) %>% 
                                    summarise(aggregate_value = mean(RC1)) %>% 
                                    ungroup() %>% 
                                    inner_join(df) %>% 
                                    select(ResponseId, Condition, all_narratives, aggregate_value)

psych::describeBy(narratives_w_theme1_inclusive$aggregate_value, group = narratives_w_theme1_inclusive$Condition)  
ind_ttest_report(narratives_w_theme1_inclusive$Condition, narratives_w_theme1_inclusive$aggregate_value)

```

